Feature#6/sign up UI
Brightcoders-Bootcamps/kata-04-reservacion-de-vuelos-team-02-nov pull request #8
Opened 2021-01-13 19:02 UTC by JacintoOrtiz15745

# Description
What did you implemented/Why did you implemented this:
-We implemented the UI Design of screen SignUp
 
 # Testing
NA

  
  ## Screenshots 
![Screenshot_1610564149](https://user-images.githubusercontent.com/47754385/104497109-7b327f00-559f-11eb-9437-3c47bac1d2c4.png)

2021-01-13 19:22 UTC, HRuvalcabaP commented
I think it's okay!

2021-01-13 19:39 UTC, HRuvalcabaP commented on ReservacionDeVuelos/src/components/atoms/SignUpTitle.js
> +import {styles} from '../../styles/SignUpStyles';
i think that is good job to import styles from other Js

2021-01-13 19:40 UTC, HRuvalcabaP submitted a review, later dismissed

2021-01-13 19:44 UTC, vmagana3 commented
It looks ok!!,  you respect the proposed design, Just the last text "Login" is not aligned correctly. I would changed that!!

2021-01-13 19:46 UTC, vmagana3 approved these changes, later dismissed

2021-01-13 19:46 UTC, vmagana3 commented on ReservacionDeVuelos/src/components/atoms/SignUpButtons.js
> +          <Text style={styles.LogInText}> Log In</Text>
I would aligned this text!!

2021-01-13 20:40 UTC, sebasdrk17 commented
It looks okay but i have a few suggestions, in the password input you should display an icon of an eye, but overall is good!

2021-01-13 21:01 UTC, sebasdrk17 approved these changes, later dismissed
Looks great!

2021-01-13 21:25 UTC, LeyaimMagma requested changes

2021-01-13 21:25 UTC, LeyaimMagma commented on ReservacionDeVuelos/src/components/atoms/SignUpForm.js
> +      </Text>
can you refactor this?

2021-01-13 21:25 UTC, LeyaimMagma commented on ReservacionDeVuelos/src/styles/SignUpStyles/index.js
> +    color: '#2D02FF',
create a _colors.js_ file to add all the colors that will be used in the app

2021-01-13 21:27 UTC, 1ng-HeberH commented on ReservacionDeVuelos/src/components/atoms/SignUpButtons.js
> +          style={[styles.googleIcon, {marginLeft: -75}]}
I would Align the google icon too.

2021-01-13 21:31 UTC, 1ng-HeberH requested changes
Nice job, but you have to  align the google icon, the log in link and also look for a way to save or refactor some code in signUptitle.js

2021-01-13 21:43 UTC, Joaquin-Niembro commented on ReservacionDeVuelos/src/components/atoms/SignUpButtons.js
> +          style={[styles.googleIcon, {marginLeft: -75}]}
Yes! i´ll work on those changes!

2021-01-13 21:43 UTC, Joaquin-Niembro commented on ReservacionDeVuelos/src/components/atoms/SignUpForm.js
> +      </Text>
Yes! I´ll work on that rigth away!

2021-01-13 22:29 UTC, JordiGN approved these changes, later dismissed
Good job in general, just the same comments as the other mentors/bright coders, but you are on fire!!! Keep working like that

2021-01-13 22:42 UTC, Joaquin-Niembro commented
i think changes have been made with success! 
![kata](https://user-images.githubusercontent.com/67522982/104518990-4aae0d80-55be-11eb-85df-710ad742c6f0.png)

2021-01-13 22:46 UTC, fernandoamz requested changes
Add all the string in the constants file all call it where you need it

2021-01-13 23:12 UTC, 1ng-HeberH approved these changes, later dismissed
Niceeeeeeeeee!!, here are some tips that will help you in future PR documentation:

1. When possible add the design view so mentors and reviewers can see how your design has to look like.
2. On the Testing section you can write a detailed description for reviewers of how to execute your changes in reviewers local.
3. When you update your screen design remember to update the screenshot so we can see the change.
Those tips helped me so much and made my work a little bit nicer jeje, nice job Jacinto

2021-01-14 00:06 UTC, JordiGN approved these changes, later dismissed

2021-01-15 15:55 UTC, fernandoamz requested changes
Create the snapshoots testing for all your components

2021-01-15 18:00 UTC, LeyaimMagma requested changes

2021-01-15 18:00 UTC, LeyaimMagma commented on ReservacionDeVuelos/src/styles/Colors.js
> +}
Add blank space here

2021-01-15 18:51 UTC, oswaldotovar32 submitted a review, later dismissed
Nice!

2021-01-15 19:09 UTC, 1ng-HeberH approved these changes, later dismissed

2021-01-15 21:28 UTC, fernandoamz submitted a review, later dismissed
Only a little recommendation, Try to install enzyme and create the snapshots with enzyme. Try to do it in your next pull request

2021-01-15 21:32 UTC, Joaquin-Niembro commented
> Only a little recommendation, Try to install enzyme and create the snapshots with enzyme. Try to do it in your next pull request

Yes! WE will use enzyme! Thanks!

2021-01-15 22:26 UTC, Joaquin-Niembro commented on ReservacionDeVuelos/src/styles/Colors.js
> +}
Could you give us more details?
Do you mean blank space like BlankSpace: ' ' ? or something else?

2021-01-18 18:49 UTC, LeyaimMagma approved these changes

2021-01-18 19:03 UTC, Joaquin-Niembro approved these changes

2021-01-18 19:06 UTC, jjcr11 approved these changes

2021-01-18 19:06 UTC, merged